# Generated by Django 2.2.28 on 2022-08-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220819_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tesst',
        ),
    ]
